FROM almalinux:9

RUN dnf -y update && \
    dnf -y install make ncurses-devel which unzip perl cpio rsync file diffutils bc bzip2 gzip sed git python3 file patch wget perl-Thread-Queue perl-Data-Dumper perl-ExtUtils-MakeMaker perl-IPC-Cmd gcc gcc-c++ && \
    dnf clean all

